### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by huqn** [mumumaster/hotel-management-system#1]
有这个数据库吗？

**Comment by z547224313** [comment]
求一份SQL文件

**Comment by huqn** [comment]
我没有呀，你要找作者




------------------ 原始邮件 ------------------
发件人: "z547224313"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 下午4:36
收件人: "mumumaster/hotel-management-system"<hotel-management-system@noreply.github.com>;
抄送: "1164204491"<1164204491@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mumumaster/hotel-management-system] mysql (#1)




求一份SQL文件

**Comment by junho16** [comment]
大佬您好，请问有数据库可以发一份吗？1967425586@qq.com，，谢谢大佬啊
